paths:
  data_root: "./data"
  good_dir: "good"
  bad_dir: "bad"
  mask_dir: "masks"
  save_model_dir: "./saved_models"

training:
  batch_size: 16
  image_size: 256
  epochs: 15
  learning_rate: 0.0001

model:
  backbone: "EfficientNetV2S"
